apiVersion: v1
kind: Service
metadata:
  name: oms-inventory-svc
  namespace: product-domain
  labels:
    app: oms-inventory
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: oms-inventory
  

